/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdmissionVoucher: typeof import('./components/admission-voucher.vue')['default']
    ApplyDetails: typeof import('./components/apply-details.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Voucher_index: typeof import('./components/voucher_index.vue')['default']
  }
}
